replicaCount: 1

bootnode:
  image:
    repository: bootnode
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 30303

jsonrpc:
  image:
    repository: jsonrpc
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: LoadBalancer
    port: 8545

miner:
  image:
    repository: miner
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 30303

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 30303
readinessProbe:
  httpGet:
    path: /
    port: 30303

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}